- name: variable
  hosts: web
  remote_user: ec2-user
  become: true
  become_user: root
  vars_prompt:
    - name: username
      prompt: " please give the username? "
      private: no
    - name: pw
      prompt: " please give the password"
      private: yes
  tasks:
   - name: add user apply password which prompt by user
     user:
       name: "{{ username }}"
       state: present
       password: "{{ pw }}"
