- name: example of notify and handler
  hosts: all
  become: true
  remote_user: ec2-user
  become_user: root
  tasks:
   - name: install httpd
     yum:
      name: httpd
      state: installed
   - name: deploy conf file
     copy:
       src: httpd.conf
       dest: /etc/httpd/conf.d/apache.conf
     notify: 
       - restart_apache
       - mail_send

  handlers:
   - name: restart service
     service:
       name: httpd
       state: restarted
     listen: restart_apache

   - name: send to mail
     command: mail -s "Testing" root@localhost
     delegate_to: localhost
     listen: mail_send

