- name: example of tags
  hosts: all
  become: true
  become_user: root
  remote_user: ec2-user
  tasks:
   - name: install ftp
     yum:
       name: ftp
       state: installed
     tags: myfav


   - name: install httpd
     yum:
      name: httpd
      state: installed
     tags: yourfav
