- name: create user in second method
  hosts: all
  become: true
  become_user: root
  remote_user: ec2-user
  vars_files: /home/ec2-user/notify-handler/userlists.yml
  tasks:
    - name: create n number of user
      user:
        name: "{{ item }}"
        state: present
      with_items: "{{ userlist }}"
