- name: example of template
  hosts: all
  become: true
  become_user: root
  remote_user: ec2-user
  tasks:
    - name: call jinja file with using template
      template:
         src: motd.j2
         dest: /etc/motd
