- name: 1st play
  hosts: web
  tasks:
   - name: example of single line format
     file: path=/tmp/data state=directory mode-0777 owner=root group=root




   - name: example of multi line format
     file: path=/tmp/data
           state=directory
           mode=0777
           owner=root
           group=root
   



    - name: example of dictionary line format
      file:
       path: /tmp/data
       state: directory
       owner: root
       group: root
       mode: 0777


